---
- name: Get hostname of target hosts
  hosts: all
  connection: local
  gather_facts: true
  tasks:
    - name: Display hostname
      debug:
        msg: "I am running on: {{ ansible_hostname }}"

    - name: Display hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ hostname_result.stdout }}"
